// Copyright [2018] [Rafał Korepta]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package ui

import (
	"mime"
	"net/http"

	"github.com/RafalKorepta/most-popular-committer/pkg/ui/data/swagger"
	assetfs "github.com/philips/go-bindata-assetfs"
	"go.uber.org/zap"
)

// serveSwagger will register `/swagger-ui` endpoint into root mux.
// This will provide visual representation of gRPC contract
// The swagger-ui is auto generated by script located in `hack/build-ui.sh`
func ServeSwagger(mux *http.ServeMux) {
	err := mime.AddExtensionType(".svg", "image/svg+xml")
	if err != nil {
		zap.L().Error("Unable to add extension type", zap.Error(err))
	}

	// Expose files in third_party/swagger-ui/ on <host>/swagger-ui
	fileServer := http.FileServer(&assetfs.AssetFS{
		Asset:    swagger.Asset,
		AssetDir: swagger.AssetDir,
		Prefix:   "third_party/swagger-ui",
	})
	prefix := "/swagger-ui/"
	mux.Handle(prefix, http.StripPrefix(prefix, fileServer))
}
